# Generated by Django 4.2.2 on 2023-06-17 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.IntegerField(choices=[(0, 'DONE'), (1, 'COMING')], default=1)),
                ('app_type', models.IntegerField(choices=[(0, 'Cavity'), (1, 'Crown'), (2, 'Surgery'), (3, 'Regular Checkup'), (4, 'Cosmetic'), (5, 'Other')], default=3)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
    ]
