# Generated by Django 4.1 on 2023-06-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_assistants_report_reportprescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='patient',
            name='lname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='prescription',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='ReportPrescription',
        ),
    ]
