# Generated by Django 4.2 on 2023-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_assistants'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
