# Generated by Django 4.2.2 on 2023-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
